name: flutter_custom_icons
description: "A modern Flutter icon font package—convert SVGs to a single font, use with a generated Dart class, and keep your app lightweight."
version: 0.0.3
homepage: https://github.com/techwithsam
repository: https://github.com/techwithsam/flutter_custom_icons
issue_tracker: https://github.com/techwithsam/flutter_custom_icons/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: iconixto
      fonts:
        - asset: assets/fonts/iconixto.ttf
    - family: feathericons
      fonts:
        - asset: assets/fonts/feathericons.ttf
    - family: fluenticons
      fonts:
        - asset: assets/fonts/fluent.ttf


