name: flutter_custom_icons
description: "Curated free SVG icons as a lightweight Flutter font pack—scalable, themeable, zero bloat."
version: 0.0.1
homepage: https://github.com/techwithsam
repository: https://github.com/techwithsam/flutter_custom_icons
issue_tracker: https://github.com/techwithsam/flutter_custom_icons/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: iconixto
      fonts:
        - asset: assets/fonts/iconixto.ttf


